# 1. Computational Graph (計算圖)

In [16]:
import tensorflow as tf

## 建立 const 

In [17]:
ts_c = tf.constant(2, name='ts_c')
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

## 建立 Variable

In [18]:
ts_x = tf.Variable(ts_c+5, name='ts_x')
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

# 2. 建立Session執行Computational Graph

In [19]:
sess = tf.Session()

In [20]:
init = tf.global_variables_initializer()
sess.run(init)

In [21]:
print(sess.run(ts_x), sess.run(ts_c))

7 2


In [22]:
print('ts_c=', ts_c.eval(session=sess))

ts_c= 2


In [23]:
print('ts_x=', ts_x.eval(session=sess))

ts_x= 7


In [24]:
sess.close()

### Session open close

In [25]:
import tensorflow as tf

ts_c = tf.constant(3, name='ts_c')
ts_x = tf.Variable(ts_c + 5, name='ts_x')

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c = ', sess.run(ts_c))
print('ts_x = ', ts_x.eval(sess))
sess.close()

ts_c =  3
ts_x =  8


### With語法開啟Session

In [26]:
import tensorflow as tf

ts_c = tf.constant(7, name='ts_c')
ts_x = tf.Variable(ts_c + 3, name='ts_x')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c = ', sess.run(ts_c))
    print('ts_x = ', ts_x.eval(sess))

ts_c =  7


ts_x =  10


# 3. placeholder

In [27]:
x = tf.placeholder("int32")
y = tf.placeholder("int32")
xy = tf.multiply(x, y)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('xy = ', sess.run(xy, feed_dict={x: 5, y: 7}))

xy =  35


# 4. 建立一維張量

In [28]:
import tensorflow as tf

ts_X = tf.Variable(tf.zeros([3]), name='ts_X')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_X = ', sess.run(ts_X, feed_dict={ts_X: [21, 3, 41]}))

ts_X =  [ 21.   3.  41.]


# 5. 建立二維張量

In [29]:
import tensorflow as tf

ts_X = tf.Variable([[32, 12, 31],
                    [12, 43, 12],
                    [13, 54, 71]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(ts_X))

[[32 12 31]
 [12 43 12]
 [13 54 71]]


# 6. 矩陣運算

In [30]:
import tensorflow as tf

X = tf.Variable([[31, 12, 14],
                 [23, 54, 25]])
Y = tf.Variable([[13, 14],
                 [22, 41],
                 [12, 16]])
XY = tf.matmul(X, Y)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XY))

[[ 835 1150]
 [1787 2936]]


### 矩陣相加

In [3]:
import tensorflow as tf

a = tf.Variable([[0.1, 0.2]])
b = tf.Variable([[-1.3, 0.4]])

Sum = b + a
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.19999993  0.60000002]]


# y = wx + b

In [31]:
import tensorflow as tf

X = tf.Variable([[1., 1., 1.]])

W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])

b = tf.Variable([[0.1, 0.2]])

Y = tf.matmul(X, W) + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Y:')
    print(sess.run(Y))

Y:
[[-1.19999993  0.60000002]]
